"use strict";
exports.__esModule = true;
var concrete_agent_1 = require("./concrete-agent");
var concrete_auctioneerA_1 = require("./concrete-auctioneerA");
var concrete_auctioneerB_1 = require("./concrete-auctioneerB");
var concrete_auctioneerC_1 = require("./concrete-auctioneerC");
var concrete_auctioneerD_1 = require("./concrete-auctioneerD");
var product_1 = require("./product");
var concreteAgent = new concrete_agent_1.ConcreteAgent();
var auctioneerA = new concrete_auctioneerA_1.ConcreteAuctioneerA();
var auctioneerB = new concrete_auctioneerB_1.ConcreteAuctioneerB();
var auctioneerC = new concrete_auctioneerC_1.ConcreteAuctioneerC();
var auctioneerD = new concrete_auctioneerD_1.ConcreteAuctioneerD();
concreteAgent.subscribe(auctioneerA);
concreteAgent.subscribe(auctioneerB);
concreteAgent.subscribe(auctioneerC);
concreteAgent.subscribe(auctioneerD);
var diamond = new product_1.Product({ nombre: "Diamante", precio: 5 });
concreteAgent.product = diamond;
concreteAgent.bidUp(auctioneerA, 10);
console.log("--------- Nueva subasta -----------");
concreteAgent.unsubscribe(auctioneerD);
var gem = new product_1.Product({ nombre: "Gema", precio: 3 });
concreteAgent.product = gem;
concreteAgent.bidUp(auctioneerB, 5);
console.log("El ganador de la subasta es \n             Producto: ".concat(diamond.nombre, "\n             Nombre: ").concat(diamond.auctionner.name, "\n             Precio: ").concat(diamond.precio));
console.log("El ganador de la subasta es  \n             Producto: ".concat(gem.nombre, "\n             Nombre: ").concat(gem.auctionner.name, "\n             Precio: ").concat(gem.precio));
